\chapter{Implementation}\label{chapter:implementation}

% TODO: explain that objective of implementation is external library
%       that doesn't leak implementation details or require knowledge of monads
\textit{
This chapter explains the implementation of \ltry\ in Haskell.
It examines how the translations from the previous chapter and the CDC library published in \cite{JonesDS07} are transformed into Haskell code.
Finally, it explores the possibility of a language extension to Haskell.
}

\section{CDC Library}
% TODO: explain the CDC library, w/ type signatures
% TODO: src in appendix or inline?

\section{Naive Implementation}

Blindly transcribing the \ltry-to-CDC translation yields a naive implementation in Haskell.
This implementation is a functioning proof-of-concept that the translation works as intended.
It does not present a high level of abstraction:

\Verbatimcode
  try :: Prompt ans b 
      -> ((t -> CC ans a) -> CC ans a1) -> (t -> CC ans a1) 
      -> CC ans a1
  try p0 m handler = withSubCont p0 (\n ->
      pushPrompt p0 (pushSubCont n (m $ \x -> throw p0 n handler x)))
  
  throw :: Prompt ans b 
        -> SubCont ans a1 b -> (t -> CC ans a1) -> t 
        -> CC ans a
  throw p0 n c m = withSubCont p0 (\_ ->
    pushPrompt p0 (pushSubCont n (c m)))
\end{Verbatim}

There is no catch construct because the exception handlers are passed directly to \mono{try}.
This is because the body of the \mono{try} block needs access to the handlers.
In order to resolve the scoping issues that \mono{throw} also needs access to the exception handlers,
calls to \mono{throw} are wrapped in a \lam-abstraction and passed to the body.
This means that throw is not directly invoked by the program but via these \lam-abstractions.

In order to run a \mono{try}-block, 
it is necessary to generate a prompt, push it, and pass it as an argument to both \mono{try} and \mono{throw}:
\begin{figure}[!h]
\Verbatimcode
example1 = runCC (do
  p <- newPrompt
  pushPrompt p (try p (\t -> return 5) (\x -> return $ x+1)))

example2 = runCC (do
  p <- newPrompt
  pushPrompt p (try p (\t -> (t 4)) (\x -> return $ x+1)))
\end{Verbatim}
\end{figure}

However, we only need a single prompt.
The same prompt is reused for setting up all the catch handlers.
This prompt should either be created and pushed at the beginning of a \mono{try} statement or it should be an unexported global constant.

This implementation also means we cannot have a variadic number of handlers.
Instead, we need to define \mono{try}, \mono{try2}, \dots\ for each case:
\Verbatimcode
try2 :: ((a -> CC ans a1) -> (a3 -> CC ans a4) -> CC ans a2)
     -> (a3 -> a2) -> (a -> a2) -> CC ans a2
try2 m h1 h2 =
  try (\t1 ->
    try (\t2 -> m t1 t2) h1)
  h2
\end{Verbatim}

Naming the handlers takes place in the names of the parameters of the abstraction in the body of \mono{try}:
\Verbatimcode
  try2 p (\name1 -> \name2 -> return 1) 
    (\x -> return $ x+2)  -- first handler bound to name1
    (\x -> return $ x+4)  -- second handler bound to name2
\end{Verbatim}
This is not like the semantics of \ltry\ which binds the names dynamically:
\[ 
  \throw n(x)
\]
will behave differently in contexts where the name $n$ is bound to different exception handlers.
To mirror this more closely, we would need a mechanism for dynamic variable binding, for example macros.

Additionally, the type signatures expose \mono{CC}, \mono{Prompt}, and \mono{SubCont}.
If we want to present a \ltry\ model of exceptions, we want to abstract over these so user does not rely on knowing them.
Unless we do this, we have \emph{leaky abstractions}.

\section{Improved Implementation}

By creating a global prompt \mono{p0}, we can implement all the operators without passing a prompt as an additional argument.
This requires exporting the \mono{Prompt} data constructor from the \mono{Prompt} module which was previously hidden.
We can then define a \mono{runTry} operation that takes a \mono{CC ans a} term constructed by \mono{try} and returns its value:
\Verbatimcode
p0 :: Prompt ans a
p0 = Prompt 0

runTry :: (forall ans. CC ans a) -> a
runTry trycc = 
  runCC $ pushPrompt p0 trycc
\end{Verbatim}

With a global prompt defined, 
the implementations of \mono{try} and \mono{throw} are much closer to the syntax of the \ltry-calculus and to the CDC translation defined in the previous chapter.

\Verbatimcode
try :: ((t -> CC ans c) -> CC ans a) -> (t -> CC ans a) -> CC ans a
try m handler =
  withSubCont p0 (\n -> pushPrompt p0 
    (pushSubCont n (m $ \x -> throw n $ handler x)))
 
throw :: SubCont ans a b -> CC ans a -> CC ans c
throw n v =
  withSubCont p0 (\_ -> pushPrompt p0 (pushSubCont n v))
\end{Verbatim}

The \mono{catch} block is still implicit in the \mono{try} function.
In order bind the correct throw to the correct handler, 
throw is still wrapped in a \lam-abstraction in the definition of try.
This also means that we still require separate definitions for multiple handlers:

\Verbatimcode
try2 m h1 h2 =
  try (\t -> 
    try (m t) h2) 
  h1
  
try3 :: ((t -> CC ans a) 
     -> (t' -> CC ans a) -> (t'' -> CC ans a) -> CC ans a)
     -> (t -> CC ans a) 
     -> (t' -> CC ans a) 
     -> (t'' -> CC ans a)
     -> CC ans a
try3 m h1 h2 h3 =
  try (\t1 -> 
    try (\t2 -> 
      try (\t3 -> m t1 t2 t3) h3) 
    h2) 
  h1
\end{Verbatim}

If we look at the type signatures, we can see the same important restrictions from the naive implementation.
The handlers must produce values of the same type. 
This will also be the type of running \mono{runCC} on the returned \mono{CC} value.

As a simple example:
\Verbatimcode
runTry $ 
  try2 (\t1 -> \t2 -> return randomNumber) 
    (\x -> return $ x + 100)
    (\x -> return $ x + 1000)
\end{Verbatim}

From this example, we can see we still have the same problem with injecting \lam-abstractions to correctly bind names.
In order to avoid this,
we need to extend the syntax of the language. 

\section{Language Extension}

The Haskell2010 standard represents $\bot$ as exceptions \cite{Haskell2010}.
Exceptions can be generated by either \mono{error} or \mono{undefined}:
\Verbatimcode
error :: String -> a
undefined :: a
\end{Verbatim}
Haskell is a lazy language which means that an expression of any type could produce an error when it is actually computed.
In a strict language, the error would be produced on assignment.
For this reason, $\bot$ is implicitly a member of every type in Haskell.
This is why the types of both \mono{error} and \mono{undefined} are universally quantified.

The simplest extension to the language is to introduce named exceptions.
Named exceptions are produced using \mono{throw name value}.
With this extension, we can introduce two other new language-level operators: \mono{try} and \mono{catch}.
\mono{try} takes a term that could produce an exception and returns a \mono{try}-block.
\mono{catch} is an infix function from a \mono{try}-block, a name, and an exception handler function to a \mono{try}-block.
If \mono{try} and \mono{catch} are both left-associative and have the same precedence,
we can construct terms with variable numbers of exception handlers:
\Verbatimcode
  try body 
    catch name1 handler1 
    ...
    catch nameN handlerN
\end{Verbatim}
\mono{throw} then takes a name and a value and returns a named exception (which can inhabit any type).

For example, we can handle errors produced by the system:

\Verbatimcode
  try (parseFile pathName) 
    catch fileNotFound (\x -> L)
    catch parseError (\x -> L')
\end{Verbatim}
and somewhere in the body of M, the corresponding errors can be thrown:
\Verbatimcode
  throw fileNotFound pathName
\end{Verbatim}

It would be trivial to implement static analysis to ensure all possible exceptions had corresponding handlers in the catch block.

% TODO: discuss implementation details
